//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisVeris.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int Id { get; set; }
        public string Metn { get; set; }
        public int Ulduzsayi { get; set; }
        public bool Status { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime Tarix { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductReview ProductReview1 { get; set; }
        public virtual ProductReview ProductReview2 { get; set; }
    }
}
